### PR TITLE
RFC2217 improvements

### PR DESCRIPTION
**Pull request by wborn**
* Rework workaround so binding can use undiscovered RFC2217 ports
* Catch UnsupportedCommOperationException

See also: 
* [community](https://community.openhab.org/t/solved-zwave-zigbee-rfc2217-remote-serial-port-howto/81633/28?u=wborn)
* https://github.com/openhab/org.openhab.binding.zwave/issues/1332
* https://github.com/openhab/openhab-core/issues/1462

### CODE REVIEW

**Comment by bodiroga** [comment]
Hi @wborn!

In my own fork I have created a branch with even more improvements for the RFC2217 connection, here you have a link to it: https://github.com/bodiroga/org.openhab.binding.zwave/tree/rfc2217-improvements

How can we merge both changes? Can I make a pull request to your own branch? Can you manually add my changes?

@cdjackson, I can confirm that this improvements work great, and with my additions, it works even better. Finally we have a RFC2217 native implementation :wink: 

Thanks guys!

**Comment by RafalLukawiecki** [comment]
I am interested in any improvements to the RFC2217 reconnection logic, many thanks for your work.

**Comment by cdjackson** [comment]
Thanks @bodiroga . I don't have any way to test this so I'll merge based on your tests. What I'd suggest is that if you've created changes on top of this PR, then you now create a new PR (adding this `also-by` signature to reference @cweitkamp and we close this. 

Thanks for looking at this - I know there are a few people that will be happy :)

**Comment by bodiroga** [comment]
Done! https://github.com/openhab/org.openhab.binding.zwave/pull/1341

**Comment by cdjackson** [comment]
Thanks @bodiroga. I'll close this and we can complete the discussion in #1341.

**Pull request closed without merging**
