### PR TITLE
Adding channel type for raw control of color

### PR DESCRIPTION
**Pull request by jjlauterbach**
Adding a channel type to support raw control of a color light.  This follows up #1675 

Signed-off-by: Jeff Lauterbach <jjlauterbach@gmail.com>

### CODE REVIEW

**Comment by jjlauterbach** [comment]
@cdjackson Will this new channel type automatically roll out to the zwave database?  Or is there another repo that needs to be updated as well?

**Comment by cdjackson** [comment]
It’s not automatic, but it should be already in the list as I added it shortly after you created this PR.

**Comment by jjlauterbach** [comment]
Not seeing it yet in the ui

**Comment by cdjackson** [comment]
I just had a look, and it is there. I did note though that the list is not sorted, so it’s right at the bottom.

**Comment by jjlauterbach** [comment]
Okay I cleared browser cache for the site and now its showing up.  Thanks

**Pull request merged**
