### PR TITLE
Update qubino_zmnhtd_0_0.xml

### PR DESCRIPTION
**Pull request by HerzScheisse**
Typo...

### CODE REVIEW

**Comment by cdjackson** [comment]
Thanks, but please update the database directly as this will be overwritten otherwise.

http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-database-guide

**Comment by HerzScheisse** [comment]
thanks Chris, yeah i tried that  and also read the guide on your page... but "To upload an XML, select the Update Device option from the tools menu in the top right of the device summary page." i dont have that "tool" menu...

**Comment by cdjackson** [comment]
I've updated your access, so you should see it now.
Note that uploading the XML won't fix the typo - the XML that gets uploaded here is not the one that is in the database - it's the one that OH saves once it has read all the data from the device so it doesn't contain any descriptions etc (basically, it populates all the endpoint related stuff at the bottom, and device level stuff at the top).

Just edit the database directly - you should now see a lot of edit buttons once logged in...

Thanks.

**Comment by HerzScheisse** [comment]
Thanks... Will have a look :)

**Pull request closed without merging**
