### PR TITLE
Set parent to 4.1.1-SNAPSHOT

### PR DESCRIPTION
**Pull request by wborn**
This may help @kaikreuzer

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Thanks, but it fails...

**Comment by wborn** [comment]
That's probably because there are no CI builds for patch releases.

**Comment by wborn** [comment]
No issues on a local build:

```
[INFO] --- install:3.1.1:install (default-install) @ org.openhab.binding.zwave ---
[INFO] Installing /home/wouter/git/openhab/org.openhab.binding.zwave/pom.xml to /home/wouter/.m2/repository/org/openhab/addons/bundles/org.openhab.binding.zwave/4.1.1-SNAPSHOT/org.openhab.binding.zwave-4.1.1-SNAPSHOT.pom
[INFO] Installing /home/wouter/git/openhab/org.openhab.binding.zwave/target/org.openhab.binding.zwave-4.1.1-SNAPSHOT.jar to /home/wouter/.m2/repository/org/openhab/addons/bundles/org.openhab.binding.zwave/4.1.1-SNAPSHOT/org.openhab.binding.zwave-4.1.1-SNAPSHOT.jar
[INFO] Installing /home/wouter/git/openhab/org.openhab.binding.zwave/target/org.openhab.binding.zwave-4.1.1-SNAPSHOT-sources.jar to /home/wouter/.m2/repository/org/openhab/addons/bundles/org.openhab.binding.zwave/4.1.1-SNAPSHOT/org.openhab.binding.zwave-4.1.1-SNAPSHOT-sources.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  33.568 s (Wall Clock)
[INFO] Finished at: 2024-01-06T16:10:25+01:00
[INFO] ------------------------------------------------------------------------
[INFO] Static code analysis summary report is available in:
[INFO] file:/home/wouter/git/openhab/org.openhab.binding.zwave/target/summary_report.html
```

**Comment by kaikreuzer** [comment]
Thanks!

**Comment by kaikreuzer** [comment]
@wborn The [sandbox build](https://ci.openhab.org/view/Sandbox/job/sandbox-openhab4-patch-release/170/console) somehow keeps failing as it cannot find the addons reactor pom 4.1.1-SNAPSHOT in the repo - which indeed isn't there. It exists for all other patch releases (e.g. 4.0.4) though. Any idea why this could be missing? I'm afraid that the currently running patch release build might fail with the same issue...

**Comment by wborn** [comment]
Maybe it got manually removed or Artifactory had some sort of outage?
Perhaps it can be fixed by manually uploading it again.

It seems the artifact was still there a few days ago if you look at the 4th step here:

https://ci.openhab.org/blue/organizations/jenkins/sandbox-openhab4-patch-release/detail/sandbox-openhab4-patch-release/165/pipeline/197/

```
+ mvn versions:set-property -Dproperty=ohc.version -DnewVersion=4.1.1 -DreleaseArgs=skipTests=true,skipChecks=true,spotless.check.skip=true -DskipChecks=true -DskipTests=true -DgenerateBackupPoms=false -Dspotless.check.skip=true -Dunleash.releaseVersion=4.1.1 -Dunleash.developmentVersion=4.1.2-SNAPSHOT -Dunleash.scmUsername=**** -Dunleash.scmPassword=**** -Drelease -P sandbox -B -DskipChecks=true
Picked up JAVA_TOOL_OPTIONS: -Dmaven.ext.class.path="/var/jenkins_home/workspace/sandbox-openhab4-patch-release/org.openhab.binding.zwave@tmp/withMaven39935c9b/pipeline-maven-spy.jar" -Dorg.jenkinsci.plugins.pipeline.maven.reportsFolder="/var/jenkins_home/workspace/sandbox-openhab4-patch-release/org.openhab.binding.zwave@tmp/withMaven39935c9b" 
[INFO] [jenkins-event-spy] Generate /var/jenkins_home/workspace/sandbox-openhab4-patch-release/org.openhab.binding.zwave@tmp/withMaven39935c9b/maven-spy-20240105-153559-65714173963639035391763.log.tmp ...
[INFO] Scanning for projects...
[INFO] Downloading from openhab-snapshots-release: https://openhab.jfrog.io/openhab/libs-snapshot-local/org/openhab/addons/org.openhab.addons.reactor/4.1.0-SNAPSHOT/maven-metadata.xml
[INFO] Downloading from sandbox-all: https://openhab.jfrog.io/openhab/sandbox-all/org/openhab/addons/org.openhab.addons.reactor/4.1.0-SNAPSHOT/maven-metadata.xml
[INFO] Downloaded from openhab-snapshots-release: https://openhab.jfrog.io/openhab/libs-snapshot-local/org/openhab/addons/org.openhab.addons.reactor/4.1.0-SNAPSHOT/maven-metadata.xml (625 B at 718 B/s)
[INFO] Downloaded from sandbox-all: https://openhab.jfrog.io/openhab/sandbox-all/org/openhab/addons/org.openhab.addons.reactor/4.1.0-SNAPSHOT/maven-metadata.xml (625 B at 718 B/s)
[INFO] Downloading from openhab-snapshots-release: https://openhab.jfrog.io/openhab/libs-snapshot-local/org/openhab/addons/org.openhab.addons.reactor/4.1.0-SNAPSHOT/org.openhab.addons.reactor-4.1.0-20231221.032506-127.pom
[INFO] Downloaded from openhab-snapshots-release: https://openhab.jfrog.io/openhab/libs-snapshot-local/org/openhab/addons/org.openhab.addons.reactor/4.1.0-SNAPSHOT/org.openhab.addons.reactor-4.1.0-20231221.032506-127.pom (28 kB at 126 kB/s)
```

It seems to be there for the 4.1.1 build :crossed_fingers: 

https://openhab.jfrog.io/ui/native/libs-release-local/org/openhab/addons/org.openhab.addons.reactor/

**Comment by kaikreuzer** [comment]
> It seems to be there for the 4.1.1 build 🤞

Ah, cool, then it should work alright and I don't care too much about the sandbox build right now. 😆

**Comment by wborn** [comment]
Too bad it seems to have failed. :disappointed: 

I also notice that other *.1-SNAPSHOT versions are missing on https://openhab.jfrog.io/ui/native/libs-snapshot-local/org/openhab/addons/org.openhab.addons.reactor/

E.g. 

3.1.1-SNAPSHOT
3.4.1-SNAPSHOT
4.0.1-SNAPSHOT

**Comment by kaikreuzer** [comment]
Yeah, too bad. Any idea how we could resume the build starting from Z-Wave? Shall we revert the parent to 4.1.0-SNAPSHOT again?

**Comment by kaikreuzer** [comment]
The 4.1.0-SNAPSHOT and the 4.1.2-SNAPSHOT are there. The one you saw before was 4.1.1 release, but not the snapshot.
 I guess we could simply revert the parent to point to 4.1.0-SNAPSHOT, then the build should be able to continue.

**Comment by wborn** [comment]
Yes it's worth a try. :+1:

**Comment by kaikreuzer** [comment]
Let's see, so far it is doing something: https://ci.openhab.org/job/openhab-patch-release/43/console

**Comment by wborn** [comment]
org.openhab.binding.zigbee probably also needs that workaround.

**Comment by kaikreuzer** [comment]
Yeah, just reverted it...

**Comment by kaikreuzer** [comment]
Seems we made it! 🎉

**Comment by wborn** [comment]
Great! :+1: 

I think I know what happens. :slightly_smiling_face:

Every time you create a x.y.0 release the pipeline assumes the next version will be x.(y+1).0-SNAPSHOT and uploads those artifacts during the release instead of x.y.1-SNAPSHOT arftifacts. So they will be missing if you manually update them to that version.

When 4.0.2 was released the parent was also using another parent, see: https://github.com/openhab/org.openhab.binding.zwave/commit/03ba56ef2977d191ee72d8cb6b6091c5cfc2a29c

It shouldn't really matter what the parent is when you start a release. Maybe that is just some oddity of Jenkins or the unleash-maven-plugin.

**Comment by kaikreuzer** [comment]
Right, it actually releases the build version (4.1.1) and then runs a test snapshot build for the next snapshot (4.1.2-SNAPSHOT) (I'm actually not sure why it does this...).

I guess I will simply keep the parent always pointing to the main release and won't do any changes to it.

**Pull request merged**
