### PR TITLE
refactored namespace to org.openhab

### PR DESCRIPTION
**Pull request by kaikreuzer**
Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
To make this repo compile again.
If you want PRs to be created against 2.5.x, you should change the default branch in the repo configuration.

**Comment by cdjackson** [comment]
Thanks. I was considering changing the default repo, but thought that might confuse people. At the moment I'm manually changing any PR to 2.5.x.

Are you changing the other repos to use 2.5.x as default? If so, I'll do the same for consistency.

**Comment by kaikreuzer** [comment]
Yes, I did that for the addons repo, see https://github.com/openhab/openhab-addons/issues/6702.

**Comment by cdjackson** [comment]
Ok, thanks @kaikreuzer

**Pull request merged**
