### PR TITLE
Implemented dummy support for CLIMATE_CONTROL_SCHEDULE

### PR DESCRIPTION
**Pull request by maxberger**
SCHEDULE_CHANGED_GET is implemented by returning a no-op report
SCHEDULE_OVERRIDE_REPORT is implemented by logging the data

Signed-off-by: Max Berger max@berger.name

### CODE REVIEW

**Comment by maxberger** [comment]
also: only unit-tested, not on prod system (but is a straight port of implementation on master)

**Comment by kaikreuzer** [comment]
@maxberger Looks as if this PR broke the build: https://ci.openhab.org/job/openHAB2-Bundles/465/org.openhab.binding$org.openhab.binding.zwave/console

**Comment by cdjackson** [comment]
CI seemed to have passed when I merged. I’ll take a look...

**Comment by cdjackson** [comment]
@kaikreuzer I think there might be a problem with CI.

When I merged this, CI passed, but after merging, the build failed. I then fixed the issue, and the build worked locally, but CI failed (and Jenkins said there were no changes!). I merged anyway, and the build is now working again.

It seems to me that the CI is building the master and not the PR branch?

**Comment by kaikreuzer** [comment]
I am just working on migrating the PR builds from the old Jenkins to the new instance. As the new instance uses a new Jenkins plugin for the Github PR building, it needs some manual work.
ZWave wasn't completely done yet, I just finished it, so let's watch the following PRs - ping me if they still do not work as expected.

**Comment by cdjackson** [comment]
Ok, thanks Kai - I thought it was already moved across. I’ll keep an eye on it next time around.

Cheers
Chris

**Pull request merged**
