### PR TITLE
Treat a failed WAKE_UP_NO_MORE_INFORMATION command as successful

### PR DESCRIPTION
**Pull request by cdjackson**
Failed WAKE_UP_NO_MORE_INFORMATION commands should not be placed back on the transaction queue - otherwise they may be sent when the device wakes again - sending it immediately to sleep!

Signed-off-by: Chris Jackson <chris@cd-jackson.com>

### CODE REVIEW

**Comment by mhilbush** [comment]
This hasn't solved the problem. I posted another log file, and some comments, on the ticket.

**Comment by pizerg** [comment]
Hi, just wanted to add that I tried this PR on our systems and it caused several unexpected issues, some sensors just went OFFLINE and I remember some of the deployments becoming quite unstable.

**Comment by mhilbush** [comment]
That's interesting. I've seen no evidence that this new code has executed at all since installing the jar 12 days ago. I have none of these messages in my debug log
```
Failed WAKE_UP_NO_MORE_INFORMATION treated as complete
```
Do you run any of your systems in DEBUG mode? If so, do you see any of the above log messages?

**Comment by cdjackson** [comment]
Please provide some logs showing why there was a problem as I don’t really see what should be the issue.

**Comment by mhilbush** [comment]
@cdjackson Just to clarify... 

You quoted my response, but I wasn't the one reporting the stability problem. I assume you meant to ask @pizerg for logs?

I had reported that it doesn't appear that the code ever executes. I attached a log to the existing ticket.

**Comment by cdjackson** [comment]
Yes - thanks mark. I’m still in Africa and trying to catch up a bit on the phone so I guess it just replied to the last message.

Should be home tomorrow.......

**Comment by cdjackson** [comment]
Ok I will likely merge this as it doesn’t seem to cause problems elsewhere and without logs I can’t investigate. If there are further problems then please provide logs.

**Comment by mhilbush** [comment]
> causing many sensors going to sleep during inclusion

@pizerg @cdjackson I mentioned this behavior the other day here.

https://github.com/openhab/org.openhab.binding.zwave/pull/1100#issuecomment-459012985

**Comment by openhab-5iver** [comment]
@cdjackson, any reason not to merge this one?

**Pull request merged**
