### PR TITLE
Fix paramater config_24_2 for Nodon msp31x1_0_0

### LINKED ISSUE #1735: Attempt to apply invalid configuration  (zwave binding)
With snapshot 2753, here is a systematic warning I got when I start my OH setup:
```

23:34:39.644 [WARN ] [b.core.thing.binding.BaseThingHandler] - Attempt to apply invalid configuration 'Configuration[{key=zwave_version; type=String; value=1.55}, {key=group_5; type=EmptyList; value=[]}, {key=group_4; type=EmptyList; value=[]}, {key=group_6; type=EmptyList; value=[]}, {key=group_1; type=ArrayList; value=[controller]}, {key=group_3; type=EmptyList; value=[]}, {key=group_2; type=EmptyList; value=[]}, {key=switchall_mode; type=BigDecimal; value=0}, {key=wakeup_node; type=BigDecimal; value=0}, {key=zwave_devicetype; type=String; value=1}, {key=config_21_1; type=BigDecimal; value=50}, {key=wakeup_interval; type=BigDecimal; value=0}, {key=zwave_deviceid; type=String; value=3}, {key=config_1_1; type=BigDecimal; value=2}, {key=zwave_nodeid; type=String; value=2}, {key=config_26_2; type=BigDecimal; value=5}, {key=config_27_1; type=BigDecimal; value=7}, {key=config_3_1; type=BigDecimal; value=3}, {key=config_22_2; type=BigDecimal; value=2000}, {key=config_4_1; type=BigDecimal; value=0}, {key=config_23_2; type=BigDecimal; value=1000}, {key=config_24_2; type=BigDecimal; value=900}, {key=node_id; type=BigDecimal; value=2}, {key=zwave_manufacturer; type=String; value=357}, {key=config_25_2; type=BigDecimal; value=20}]' on thing 'zwave:nodon_msp31x1_00_000:controller:node2' blocked. This is most likely a bug.
```
Probably something related to recent changes with configuration handling ?

### PR DESCRIPTION
**Pull request by lolodomo**
Fix #1735

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by cdjackson** [comment]
Thanks, but please can you update this in the database rather than as a PR. If the database isn't updated, then this change will be overwritten within a few days.

**Comment by lolodomo** [comment]
Sorry, I even do not know where is the database !
Where can I find it ?

**Comment by cdjackson** [comment]
There are many links though the documentation to it, but it is here -:

https://opensmarthouse.org/zwavedatabase

I will add this option since you don't have an account, but if you find more issues like this it might be worth creating a login so you can make any changes...

**Comment by lolodomo** [comment]
> I will add this option since you don't have an account, but if you find more issues like this it might be worth creating a login so you can make any changes...

This is apparently the only error found for my Z-Wave network.

**Pull request closed without merging**
