### PR TITLE
Homeseer HSDS100 Updates

### PR DESCRIPTION
**Pull request by dmize**
Fixed channels, default associations, association groups.
I have tested this locally and it is working.

### CODE REVIEW

**Comment by cdjackson** [comment]
Please make the updates into the database at www.cd-jackson.com and not directly through a PR here.
Thanks.

**Comment by dmize** [comment]
I've updated the database as well.  Although I find it more difficult to update the database and know that it works.  Do you not take PRs anymore?

**Comment by cdjackson** [comment]
The problem with PRs is that they will be overwritten when the database is updated. So I can merge your PR, and it might last a few days or a week or two before being overwritten with the data from the database. For this reason I really prefer to only use exports from the database.

Also, if you do a PR here to the master, then it will not be merged into the development version which uses a slightly different database format - if the data is entered into the database, then we get OH1, and OH2 files all created from the same source.

Why can't you test the database output? I mean, most people don't bother, but if you are testing the XML created by yourself, then it's simple enough to use the database XML - just press the export button.

**Comment by dmize** [comment]
That makes sense.  It took a bit of trial and error to get this device working.  I originally uploaded the xml created when I added it but it didn't work right.  After some research through your interactions with others on the forum I started looking at their database xml and figure out what to do to fix it.  If I had to make each edit on the site and then export it that would have been tedious.  I'll take a look at the export to make sure it aligns with what I have here.  I'm not trying to be a pain, in fact, I'm trying to be helpful.

Thanks for your assistance.

**Comment by dmize** [comment]
Ok, I reviewed the exported XML and it looks good.  Do you want to reject this PR?

**Comment by cdjackson** [comment]
Ok, thanks. I'll be doing a database update tonight so it should go in with that.

Thanks.

**Pull request closed without merging**
