### PR TITLE
Everspring AD146: Add channel for setting output mode config parameter

### PR DESCRIPTION
**Pull request by rickynils**
Signed-off-by: Rickard Nilsson <rickynils@gmail.com> (github: rickynils)

### CODE REVIEW

**Comment by cdjackson** [comment]
Thanks for Please can you make the changes directly into the database -:

http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-database-guide

You won't be able to use the specific channel type so please just use the ```config_decimal``` type.

Thanks.

**Comment by rickynils** [comment]
@cdjackson Sorry for not researching how to update the DB first :) I'll register and update the database through your site.

**Comment by cdjackson** [comment]
No problem. Ive also updated your access on the database site so you should be good to go there.Any problems, just give me a shout....

**Comment by rickynils** [comment]
@cdjackson Thanks! I've uploaded the XML for the device: http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/24

**Pull request closed without merging**
