### PR TITLE
Added the Devolo MT2756 flood sensor

### PR DESCRIPTION
**Pull request by jucs**
Dear Chris,

I've tried to add the MT2756 flood sensor as discussed in this thread:

https://community.openhab.org/t/devolo-flood-sensor-doesnt-seem-to-be-in-the-z-wave-database/18638/5

I hope I got it about right, I haven't been sure what to put in the "dbReference" reference field (so I left it the way it was for the PAT02c).

Thanks again for your help :-)!

Greetings,
Julian

### CODE REVIEW

**Comment by cdjackson** [comment]
Hi Julian,
Sorry - I missed that thread. We need to get it into the online database - if I accept the PR, then it will be removed again in the near future as the XML files are exported directly from the database. If your device isn’t in the database, then it will be removed.

If you have the XML from the device (i.e. the one OH generates) then it’s easy to add.  If you have registered on www.cd-jackson.com and don’t have permission, then just let me know and I can give you access.

Cheers
Chris

**Comment by jucs** [comment]
Dear Chris,

thanks for your fast reply :-). I indeed have the XML file from OH. I've registered on your database website, my username is "jucs". Please give me permission to add the device.

Greetings,
Julian

**Comment by cdjackson** [comment]
Hi Julian,
I’ve updated your access so you should be able to add the device. If it’s a copy of the other device, then you can also copy the config in the database itself. So, you should create a new device by uploading the XML from OH, then you should be able to go to the new entry and click on the tools button in the top right and there should be an option to copy config from another device.

Any problems, just let me know.

Cheers
Chris

**Comment by jucs** [comment]
Dear Chris,

did all these step and finally clicked on "Request Review" :-).

Greetings,
Julian

**Comment by cdjackson** [comment]
Thanks - looks fine.  Do you have a link to any information on the device? If possible I’d like to upload a PDF manual but can’t find a devolo manual on the web (I only did a quick search!).

**Comment by jucs** [comment]
[44305_Home_Control_Wassermelder_0516_en_online.pdf](https://github.com/openhab
Yes, here is the product description, manual, etc.:

/org.openhab.binding.zwave/files/670692/44305_Home_Control_Wassermelder_0516_en_online.pdf)
[Datasheet_devolo_Home_Control_Water_Sensor_EU.pdf](https://github.com/openhab/org.openhab.binding.zwave/files/670691/Datasheet_devolo_Home_Control_Water_Sensor_EU.pdf)
[hc_Produktblatt_Wassermelder_EU_screen.pdf](https://github.com/openhab/org.openhab.binding.zwave/files/670693/hc_Produktblatt_Wassermelder_EU_screen.pdf)
[MT_2756_Flood_Sensor_en_de.pdf](https://github.com/openhab/org.openhab.binding.zwave/files/670690/MT_2756_Flood_Sensor_en_de.pdf)

**Comment by cdjackson** [comment]
Thanks - I’ll add this device to the binding tonight.

**Comment by jucs** [comment]
Thanks :)

**Pull request closed without merging**
