### PR TITLE
Update rtc_ct30_0_0.xml

### PR DESCRIPTION
**Pull request by asilva732**
Adding new reference

### CODE REVIEW

**Comment by cdjackson** [comment]
Hi,
Information on updating the database is here  (http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-database-guide <http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-database-guide>).  Please can you update directly in the database.

Thanks

**Comment by asilva732** [comment]
I cannot manually enter this in your website. I also don't have an XML file to upload as a workaround.

**Comment by cdjackson** [comment]
If you don’t have access, then you need to register and then request access (as is written in bold in the instructions ;) ).

You don’t need to have an XML - you can just edit the database and add the references.  If we don’t do the changes in the database then any changes will be overwritten in future.

**Comment by asilva732** [comment]
Understood.

Made an account which requires contacting you for the edit priveledges.

aasilva80

Thanks

**Comment by cdjackson** [comment]
I’ve updated your access so you should be good to go.

Thanks.

**Comment by asilva732** [comment]
Thank you.

Interestingly enough, when saving the change, it looks like the references get sorted (which I guess looks like I modified more than I claimed to do)

And how to know what Z-wave binding Snapshot version these changes will be implemented to? Sorry I am still relatively new to this and am not sure if a changelog is provided with every update.

**Comment by cdjackson** [comment]
I will look to implement this probably Tuesday when I’m back from the openHAB event here in Germany. If you watch the PRs in the zwave repo you should see the “Database update” PR and I will then trigger a build just after that.

Thanks
Chris

**Comment by cdjackson** [comment]
Closing as changes will be incorporated into next database update (later today)

**Comment by asilva732** [comment]
Update:

Database was able to sync the plugin switches. It also read the thermostat node. 

Though for some reason, I lost the Tstat node. Weird

**Pull request closed without merging**
