### PR TITLE
Database update

### PR DESCRIPTION
**Pull request by cdjackson**
Signed-off-by: Chris Jackson <chris@cd-jackson.com>

### CODE REVIEW

**Comment by mhilbush** [comment]
@cdjackson In this PR I see some changes to the heal process (neighbor update). Are these changes related to https://github.com/openhab/org.openhab.binding.zwave/pull/1174#issue-281826472. Did you mean to include these?

**Comment by cdjackson** [comment]
Goops - no, I didn’t mean to include them in this - it was meant to be another PR… It doesn’t really matter I guess - and at the moment builds are broken :(

**Comment by mhilbush** [comment]
> builds are broken

Yeah, saw that. Seems to happen a lot these days... ☹️ 

If you decide to not revert the heal changes, I can try doing a heal on one of my battery devices and monitor the result. Once the builds are working again...

I'll add any observations to the other PR. Ok?

**Comment by cdjackson** [comment]
Yep - that’s fine - thanks Mark.

**Pull request merged**
