### PR TITLE
Create willis_zen21_0_0.xml

### PR DESCRIPTION
**Pull request by aristopopulus**
Add support to Zooz Z-Wave On / Off Light Switch ZEN21

### CODE REVIEW

**Comment by cdjackson** [comment]
Please add this to the online database -:
http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-database-guide

Thanks

**Comment by aristopopulus** [comment]
http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/544

**Comment by cdjackson** [comment]
Ok, then please remove the errors so it can be finalised.

**Comment by aristopopulus** [comment]
We Can´t, this is the error Command Class "ASSOCIATION" in endpoint 0 is duplicated! but there is not an option to delete the Command Class, could you tell me how can I delete it?

**Comment by aristopopulus** [comment]
I don´t know how we do but it is now fixed, if it was you, thanks http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/544

**Comment by cdjackson** [comment]
Yes - I removed the error. If this is a paste straight from the database I’ll merge it now.

**Comment by aristopopulus** [comment]
Yes, It was coppied straight from the database

**Comment by cristhiampaul** [comment]
Why my OH2 still not recognize the thing, I uninstall and install the z-wave binding and nothing.

**Comment by cristhiampaul** [comment]
image

image

**Comment by dmize** [comment]
Did you delete the thing and let it be discovered again?

**Comment by cristhiampaul** [comment]
Yes, delete and add, exclude and include.

image

**Comment by dmize** [comment]
sorry, I see now that he just merged this.  It will be compiled in the nightly and you will need to install a new version of the binding once that happens.

**Comment by cdjackson** [comment]
I just triggered a build manually - hopefully it should be done in 30 minutes or so.

**Pull request merged**
