### PR TITLE
Implement reconnection to ZWave serial stick (#979)

### PR DESCRIPTION
**Pull request by dottedmag**
Keep probing the port if the stick is not ready on startup or an error has been
received from the serial port.

### CODE REVIEW

**Comment by dottedmag** [comment]
I haven't touched Java since 2002, so please let me know if something has changed since.

**Comment by cdjackson** [comment]
Thanks - just a few initial comments that will need to be resolved before proceeding.

I don't think this will work properly. How do you reinitialise the device once it is plugged in? There is a lot more to do than just to initialise the serial port. You probably need to close down the controller and restart it - or at leat ensure that the reinitialisation is completed. This could be quite messy to achieve (although I've not looked at it, so maybe it's not too hard).

Please sign your commit and PR.

Please ensure any PR is against the development branch, and not master.

**Comment by dottedmag** [comment]
I don't see where `ZWaveController` ever removes `ZWaveNode`s from itself, so I'll work on it a little bit more to understand.

**Comment by cdjackson** [comment]
No - this is sort of my point. The software wasn’t designed to be restarted like this, so I want to be sure that it’s not going to cause any issue. It might be fine as it is, and I’d certainly be happy to avoid changing too much, but I’d like to be sure that if we merge this, it doesn’t cause a load of unwanted issues as soon as more people start using it ;)

Thanks - let me know how you get on and if you have any questions, just fire away….

**Comment by bodiroga** [comment]
Hi @dottedmag!

Are you still interested in supporting this feature? It would be really cool if we could add it for the next version of openHAB (2.5, not 2.4, of course). I have implemented a reconnect feature in my "tcp_controller" branch (https://github.com/bodiroga/org.openhab.binding.zwave/tree/tcp-controller) and it is working great.

My suggestion is to modify the ZWaveThingHandler's bridgeStatusChanged method like this:

```java
ZWaveControllerHandler bridgeHandler = (ZWaveControllerHandler) getBridge().getHandler();

        if (bridgeStatusInfo.getStatus() != ThingStatus.ONLINE) {
            updateStatus(ThingStatus.OFFLINE, ThingStatusDetail.BRIDGE_OFFLINE,
                    getI18nConstant(ZWaveBindingConstants.OFFLINE_CTLR_OFFLINE));
            logger.debug("NODE {}: Controller is not online.", nodeId, bridgeStatusInfo.getStatus());
            synchronized (pollingSync) {
                if (pollingJob != null) {
                    pollingJob.cancel(true);
                    pollingJob = null;
                }
            }
            controllerHandler = null;
            if (bridgeHandler != null) {
                bridgeHandler.removeEventListener(this);
            }
            return;
        }

        logger.debug("NODE {}: Controller is ONLINE. Starting device initialisation.", nodeId);

```

Bye!

**Comment by dottedmag** [comment]
@bodiroga I definitely am, though I don't have the time right now to really read all the code and understand what else might be needed as @cdjackson has explained.

I'll rebase the patch to the new version, add with your changes and let it hang here for a while until I or someone else figures the rest out.

**Comment by cdjackson** [comment]
Closing as no changes for 8 months and also superceded by #1210

**Pull request closed without merging**
