### PR TITLE
Added missing meter_reset channels

### PR DESCRIPTION
**Pull request by TheNetStriker**
I’ve added some missing meter_reset channels. I already tested this and
it works perfectly. Please add this to the main repository.

Signed-off-by: David Masshardt <david@masshardt.ch> (github:
TheNetStriker)

### CODE REVIEW

**Comment by cdjackson** [comment]
Have you added these additions to the database (www.cd-jackson.com)? I updated last night so it should be included if so.

**Comment by TheNetStriker** [comment]
I've just checked the device database and the meter_reset command does not exist in those devices. I just created an Account (Username TheNetStriker) but I don't have the right to change something. Can you give me the right or can you add the changes yourself?

**Comment by cdjackson** [comment]
Thanks - I’ve updated your access.

Cheers
Chris

**Comment by TheNetStriker** [comment]
I've just uploaded the XML's and requested a review, I hope I did everything right. Sadly I only have FGRM222 devices with version 24.24 and 25.25, so I can't upload the file for those devices, but I assume they also support the reset command.

I also just noticed that my 24.24 device doesn't get recognized any more. Do you have any idea what could cause this problem? I've tried to add the device several times in PaperUI. (It worked with the 2.0 release of the binding and I just added the reset command)

**Comment by cdjackson** [comment]
I think this is now all included in the database (thanks), so closing...

**Pull request closed without merging**
