### PR TITLE
Address multichannel CC with only EP 0

### PR DESCRIPTION
**Pull request by apella12**
I think this will work based on your guidance.  I just made the minimum amount of changes. As I understand it only the GET will be returned and processed to the node advancer, so it will finish?

There does appear to another community post on the same topic(Shelly mini). As an editorial, I see lots of posts on Shelly they seem to be popular, but have issues.

Signed-off-by: Bob Eckhoff <katmandodo@yahoo.com>

### CODE REVIEW

**Comment by apella12** [comment]
Tested locally on a multichannel device and it still works, so that's positive.  I don't have the problem device.

**Comment by cdjackson** [comment]
Thanks @apella12 - if I understand correctly from what I read on the forum, this is now working and results in the XML being produced? If so, I'll merge...

**Comment by apella12** [comment]
Yes it did work for the problem device to produce a OH XML.   OP has subsequently added device 1648. I also config the multichannel CC on that device to remove.  The PR changes also didn't affect a working multichannel device that I tested.  I think it is good to go unless you see something else.

**Comment by cdjackson** [comment]
Thanks @apella12

**Pull request merged**
