### PR TITLE
ThingHandlerFactory: start on demand

### PR DESCRIPTION
**Pull request by lolodomo**
Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
It seems to have fixed the problem I got at OH startup.
But of course, using now a new jar file in folder addons could have changed the order of started bundles.
But by the way, this is better to not have this "immediate = true".

**Comment by cdjackson** [comment]
Shouldn’t we have a common way to implement this in openHAB? If I look in the openhab addons most binding seem to have immediate=true so it seems strange to change this.

**Comment by lolodomo** [comment]
In OH2, most of them have not "immediate = true" and i just created a PR to suppress "immediate = true" from the 15 bindings for which it was still there.
See the discussion in OH2 and the multiple previous PR that already tried to suppress "immediate = true".

**Comment by cdjackson** [comment]
Ok, thanks. Please link the other PR and once it’s merged I’ll merge this.

**Comment by lolodomo** [comment]
Here is the opned OH2 PR: https://github.com/openhab/openhab2-addons/pull/5855
And the discussion: https://github.com/openhab/openhab2-addons/issues/5852

**Comment by openhab-5iver** [comment]
@lolodomo, should the same be done for [zigbee](https://github.com/openhab/org.openhab.binding.zigbee/search?q=thinghandlerfactory&unscoped_q=thinghandlerfactory) too?

**Comment by lolodomo** [comment]
Yes, of course.

**Comment by lolodomo** [comment]
The OH2 PR is now merged. 
Please do the same for this one.

**Comment by cdjackson** [comment]
Thanks.

**Comment by lolodomo** [comment]
Can you update the zigbee binding if necessary?

**Pull request merged**
