### PR TITLE
Removed extraneous byte in network security key example

### PR DESCRIPTION
**Pull request by vzorglub**

### CODE REVIEW

**Comment by cdjackson** [comment]
Thanks. I guess it's probably also fixing the other instances of this? Also, please can you sign your commit (see the contribution guidelines).

**Comment by vzorglub** [comment]
These small patches come under the [Small Patch Exception](Small Patch Exception)
And I should have to sign for these. I have no idea on how to do it anyway :smile:

**Comment by cdjackson** [comment]
Yes, I would accept that, although it is better to sign and given you have to update the PR anyway, why not just add the signature. It is easy to do did you read the contributors notes as I suggested?)

**Comment by cdjackson** [comment]
@vzorglub do you plan to update this PR?

**Comment by vzorglub** [comment]
How do I do that?

**Comment by cdjackson** [comment]
All that needs to be done is to update the file with the additional changes so that everything is consistent.

**Comment by vzorglub** [comment]
I have never done such a thing. I wouldn't know where to start. 
I just did what I normally do when doing a small correction on the docs.

**Comment by cdjackson** [comment]
Then let’s just close this an just do another PR with the corrections.

**Comment by vzorglub** [comment]
Done #1129

**Pull request closed without merging**
