### PR TITLE
Fix XStream security framework not initialized warnings

### LINKED ISSUE #1476: XStream not initalized
* OH3 Version: 3.0.0 stable docker
* Binding Version (if SNAPSHOT, provide compile time as found on the filename in the console): 3.0.0

At runtime the log shows the error: Security framework of XStream not explicitly initialized, using predefined black list on your own risk.

According to this post: https://community.openhab.org/t/xstream-not-initalized/110879 it would be solved in the stable version 3.0.0, unfortunately it doesn't. It’s probably the unsafe usage of XStream by the Z-Wave binding: https://github.com/openhab/org.openhab.binding.zwave/blob/1bf81ffd0f70cfd293b6f40140db50591a962ade/src/main/java/org/openhab/binding/zwave/internal/protocol/initialization/ZWaveNodeSerializer.java#L46

### PR DESCRIPTION
**Pull request by wborn**
Fixes #1476

See also this [community thread](https://community.openhab.org/t/xstream-not-initalized/110879?u=wborn)

### CODE REVIEW

**Comment by cdjackson** [comment]
Thanks @watou

**Comment by watou** [comment]
Thanks @wborn! Nice to get a typo hello via GitHub. Thanks to Chris and Wouter for great work. I miss the project in a few ways.

**Comment by cdjackson** [comment]
I'll blame autocomplete (and Hi @watou - long time no see - hope you're well...).

**Comment by wborn** [comment]
Yes hello to you too @watou! I hope I don't miss more messages because of these typo's. 😉

**Pull request merged**
