### PR TITLE
manual database update

### PR DESCRIPTION
**Pull request by bwosborne2**
Manual database update.
Process scripts broke due to renaming from "master" to "main".

### CODE REVIEW

**Comment by bwosborne2** [comment]
This is a temporary workaround for issue #1531 
It is NOT a complete fix.

**Comment by cdjackson** [comment]
Thanks Bruce.

**Comment by bwosborne2** [comment]
I updated the script branch & tried from the web menu. It did not work and, I assume I would need to download the scripts & run locally.

I figured this could buy some time.

**Comment by cdjackson** [comment]
As I’ve mentioned in the past, you can’t trigger the update from the web ui - that doesn’t work as there needs to be a decoupling between the UI and the script. It can only be done through ssh.

**Comment by cdjackson** [comment]
Bruce - I tried to run your script, but get file not found error now. I'll try and take a look later tonight but did you rename it or something?

**Comment by bwosborne2** [comment]
All I did in the OH3 script was change `master` to `main`

**Comment by cdjackson** [comment]
Ok, this file seems to be gone now so I'll need to regenerate it as I don't think I have it elsewhere - I don't suppose you had a copy?

**Comment by bwosborne2** [comment]
I just used the online editor. I do not know how it was deleted. It should be the same as the OH2 one except for the branches, correct?

**Comment by cdjackson** [comment]
Ok, I'm not sure how it got deleted :(

I have a feeling there were another couple of small changes to make it work on OH3, but I can't remember now as it implemented 6 months back. Probably the folders also have to change for starters - I forget what else.

I won't be able to look at this for a week or so.

**Comment by bwosborne2** [comment]
I was just thinking it may be in a backup.
I just tried the 3.1.0 SNAPSHOT with a 3.0.0- snapshot serial ( I had it available) on 3.0.1 Docker and it complains about the zsmoke xml :(
Since it is Docker, going to try 3.1.0 SNAPSHOT OH

**Pull request merged**
