### PR TITLE
Database update

### PR DESCRIPTION
**Pull request by cdjackson**
Signed-off-by: Chris Jackson <chris@cd-jackson.com>

### CODE REVIEW

**Comment by apella12** [comment]
This seems stuck.  Do you know why?

**Comment by cdjackson** [comment]
It's not "stuck" as such - I just didn't get time to check and merge it before a couple of days travel, and then I forgot - sorry.

**Comment by apella12** [comment]
No worries.  Someone on the forum (who recently added a device) asked and I thought it looked unusual that a PR from you didn't merge more or less automatically.  Thanks !

**Comment by cdjackson** [comment]
No probs - and thanks for the "ping" :)

**Pull request merged**
