### PR TITLE
Add conversion for differential white report

### PR DESCRIPTION
**Pull request by Aaargh20318**
On devices with a differential white channel (warm+cold white), such as the Zipato Bulb 2, the value of the color temperature channel always resets to 0 after updating. While the color temperature value is converted to a warm + cold value when setting the value, the reverse conversion isn't performed when receiving the report back from the device. 

This PR adds the reverse conversion so the channel is updated correctly.

### CODE REVIEW

**Review by cdjackson — CHANGES_REQUESTED** [review]
This looks fine, but please format the code using the formatter.

**Comment by Aaargh20318** [comment]
I ran the formatter and it changed nearly every file for some reason. Makes the patch a bit messy.

**Comment by cdjackson** [comment]
Are you sure you are using the correct formatter for OH? Either that or manually format it - at the moment it's really not good as all the indentation is messed up.

**Comment by Aaargh20318** [comment]
> Are you sure you are using the correct formatter for OH? Either that or manually format it - at the moment it's really not good as all the indentation is messed up.

I ran `mvn spotless:apply`, as that's what's configured in the POM. 

Should I be using a different formatter ?

**Comment by cdjackson** [comment]
I normally use the Eclipse IDE formatter. In any case it needs resolving before merging please.

**Comment by Aaargh20318** [comment]
I'll revert the formatting changes and just do it manually.

**Comment by cdjackson** [comment]
Thanks. This looks fine now.

**Review by cdjackson — APPROVED** [review]

**Pull request merged**
