### PR TITLE
[OH3] Add new serial reconnect logic

### PR DESCRIPTION
**Pull request by bodiroga**
Hi @cdjackson!

With the new nrjavaserial library version that will be available in OH3 (@wborn, this is correct, isn't it?), I think that we can improve the serial reconnect logic and remove the workaround pointed out in #1332.

The new reconnect logic just checks the serial port when the library detects that the USB device has been removed. For that, we make use of the ```serialEvent``` callback, which no longer stresses the CPU and is able to detect when the Z-Wave controller is unplugged. We also get rid of the periodic watchSerialPort thread and the reconnect task is only executed when needed.

The PR has been done against the 2.5.x branch, but, in case you are interested in it, it should be merged in a separate branch. **Warning**: it will not work with the nrjavaserial version included in openHAB 2.5.x!

Many thanks for your attention and thank you also @wborn for the work you are doing with the serial library :wink: 

Signed-off-by: Aitor Iturrioz <riturrioz@gmail.com>

### CODE REVIEW

**Comment by wborn** [comment]
That's a good thing the workaround can finally be removed! I'll make sure the library is updated for OH3. I think most reconnection bugs will be solved when https://github.com/NeuronRobotics/nrjavaserial/issues/111 is also fixed.

**Comment by bodiroga** [comment]
Does anybody know what is going on with the DCO check? :confused:

**Comment by wborn** [comment]
It doesn't matter much now because you'll probably need to rebase anyways once the changes from the 2.5.x branch are merged to the master branch. I think that may also still take a while. :wink:

**Comment by ghys** [comment]
I can confirm these changes seem to solve the endless disconnect/reconnect loop I experienced with nrjavaserial 5.0.2 described at https://community.openhab.org/t/z-wave-controller-keeps-resetting-with-nrjavaserial-5-0-2-in-oh3/99628 👍

**Comment by wborn** [comment]
Nice! Thanks for the feedback. :slightly_smiling_face:

**Comment by wborn** [comment]
nrjavaserial 5.2.1 got merged in https://github.com/openhab/openhab-core/pull/1503.

**Comment by bodiroga** [comment]
Hi guys!

I have improved the reconnection logic for RFC2217 connections, as now the binding is able to detect very fast (< 1 second) that the RFC2217 server is down. I have been doing tests for more than 2 hours (plugging and unplugging the Z-Wave stick) with no problem, and the CPU consumption has been low and stable. It is awesome to see that the binding will accept local and remote connections while being able to reconnect in both cases.

Looking forward to your feedback, @cdjackson, but don't worry, there is no rush :+1:

**Comment by cdjackson** [comment]
@bodiroga this seems to have merge conflicts now - I think it must have been as a result of the previous PR of yours that was merged.

**Comment by bodiroga** [comment]
Ok, it seems that I have been able to resolve the conflicts without breaking the branch :+1: 

After your latests comments in the webui branch, it seems that you are now more interested in trying OH3, right? :wink: 

Thanks for your support @cdjackson!

**Comment by cdjackson** [comment]
I've changed the base on this to OH3.

**Comment by bodiroga** [comment]
Awesome!

**Pull request merged**
