### PR TITLE
[dev] Database update - RESYNC

### PR DESCRIPTION
**Pull request by cdjackson**
Signed-off-by: Chris Jackson <chris@cd-jackson.com>

### CODE REVIEW

**Comment by mhilbush** [comment]
I was a couple minutes too late with my change to FGD212...

**Comment by cdjackson** [comment]
Yeah - I just saw them. I’ll get them in here before I merge this, but the merge into master will have to wait till the next round…

And thanks for doing this :)

**Comment by mhilbush** [comment]
I guess I need to start waking up earlier.  LOL

**Comment by cdjackson** [comment]
Speak to @openhab-5iver - he seems to have perfected being always awake ;)

**Comment by cdjackson** [comment]
Updated with the FGD212 - is that all your changes done for now @mhilbush ?

**Comment by mhilbush** [comment]
Yes.

**Comment by cdjackson** [comment]
@mhilbush @openhab-5iver what do you think? I've restructured the database into separate folders per manufacturer as we're heading towards 800 entries now and it's just too unwieldy (IMHO) in one folder.

I also removed the manufacturer off the filename itself.

Happy to hear any thoughts before I merge ;)

**Comment by openhab-5iver** [comment]
I can't think of any reason not to do this. Do you have concerns about it?

**Comment by cdjackson** [comment]
No - no concerns. I initially thought that everything needed to be in one folder for ESH to find them, but I checked this morning and it does recurse the folders.  I did a quick restart and it seems to load the files fine.

**Comment by openhab-5iver** [comment]
If you'd like, send me the jar and I can smoke test before you post it.

**Comment by cdjackson** [comment]
Thanks. I’ve put it in my usual download folder - filename is org.openhab.binding.zwave_2.3.0.201803111303.jar.

**Comment by mhilbush** [comment]
I'm a little late joining the conversation, but I agree that it makes sense to organize into individual folders per manufacturer. I didn't realize it was up to 800 entries. Seems like new devices are coming out almost daily...

On a related topic, I also agree with @openhab-5iver that the ability to see the history of database updates would be great. I currently do this by sorting through the commits, which works, but is less than ideal.

**Comment by cdjackson** [comment]
The easiest way to see the history is to go to the XML file you’re interested in, and click on history, or click on blame. History will give you the list of changes, and blame will show each line that changed with a date (but it won’t show removals). 

I agree that something a bit nicer would be, well, nicer, but it’s also quite a bit more work. I could feed the whole thing in to a git repo and record changes every time someone changes anything, but that might slow things down even more. I’ll have a think some more...

Currently there are 713 devices exported, but yes, it’s going up quite fast at the moment!

**Comment by openhab-5iver** [comment]
Restarted OH with the 2.3.0.201803111303 jar, deleted 119 Things, and there's nothing out of the ordinary in the log. Everything seems to function as it did, so looks good to me.

**Pull request merged**
