### PR TITLE
Adding sunricher zv9032a_0_0.xml

### PR DESCRIPTION
**Pull request by krispypen**
It's this device: https://www.robbshop.nl/robb-smarrt-bewegingsmelder-temperatuursensor-z-wave

I received access to https://opensmarthouse.org/ but I always get a permission error when creating a device. So i'm adding it this way.

### CODE REVIEW

**Comment by apella12** [comment]
`I received access`  Did you open a ticket to get write access?  

Anyway, I believe adding this way will not persist when the DB is merged into the binding.

**Comment by krispypen** [comment]
I opened a new ticket to ask write access. I do see the "create device" button but when I submit that form it fails with a 409 error

**Comment by apella12** [comment]
One more question.  The device XML in this PR isn't the right one to load.  You did load the xml from your userdata/zwave folder?

**Comment by krispypen** [comment]
oooh, that explains 🤦‍♂️ Sorry, I'll close this MR and try it again via opensmarthouse.org
Thanks!

**Pull request closed without merging**
